### ISSUE TITLE
Core recommendation for NRF52840

### ISSUE THREAD

**Issue by dazhbog** [arduino/ArduinoCore-nRF528x-mbedos#4]
Hey guys,

Im seeing that you are releasing the Arduino Nano 33 BLE (NRF52840). Well done!

My question is, is this the core to use for that board? What is the level of stability and peripheral support?

How does this compare with adafruits core [here?](https://github.com/adafruit/Adafruit_nRF52_Arduino) 

Thanks!

**Comment by facchinm** [comment]
Hi @dazhbog ,
the two cores are completely different :slightly_smiling_face: 
This is the right one for the Nano 33 BLE; it is not based on Nordic softdevice as Adafruit's one so it's missing the DFU via BLE functionality but all the peripherals are supported using open source alternatives.
Since it's based on mbed OS, the stability is battle proven.
