### ISSUE TITLE
[SPI] missing  setClockDivider, setBitOrder, and setDataMode API's

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/ArduinoCore-nRF528x-mbedos#5]
Originally reported by @LittleHobbyShop here: https://github.com/adafruit/Adafruit-GFX-Library/issues/242

@facchinm any thoughts on this?

**Comment by facchinm** [comment]
Indeed, setClockDivider(), setBitOrder(), and setDataMode() were marked as deprecated since the introduction of SPISettings and thus not included in https://github.com/arduino/ArduinoCore-API . I'm a bit concerned in reintroducing them and I'd prefer if GFX library could be patched.
The patch shouldn't hurt any core since everyone already implements SPISettings

**Comment by facchinm** [comment]
Nevermind, I found the issue; SPI.h is missing `SPI_HAS_TRANSACTION` define. The library compiles fine after defining it; I'm going to add it to API repo (since transactions support is compulsory) and publish an updated core when done :wink:

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino/ArduinoCore-API/commit/862fb23829fe333e8218934cd3437ac16246231f and tagged core 1.1.1

**Comment by ladyada** [comment]
thanks! that was easy :)
