### ISSUE TITLE
Error linking CMSIS library: libarm_cortexM4lf_math.a using -mfloat-abi=hard compile flag

### ISSUE THREAD

**Issue by leomonan** [arduino/ArduinoCore-nRF528x-mbedos#79]
Hi,
   My APP want to use -mfloat-abi=hard float VFP, so I used libarm_cortexM4lf_math.a, but build reports error:

>  error: /Users/CMSIS/Lib/GCC/libarm_cortexM4lf_math.a(arm_add_f32.o) uses VFP register arguments, /var/folders/d/Engine.ino.elf does not.

   Could you please tell me how to resolve this?

**Comment by facchinm** [comment]
Hi @leomonan , the core is built with `softfp` abi (the name is a bit misleading since it uses the floating point hardware anyway) so you can't link hardfp libraries.
Since this happens all the time, all ARM precompiled libraries are provided in both softfp and hard ABI , just find the correct one and linking will be fine
